<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.klindziuk.TriangleTestLab.TriangleTest" tests="4" time="0.043" ignored="0" failures="0" timestamp="22 фев 2017 17:11:26 GMT" skipped="0" hostname="Pk" errors="3">
  <testcase name="constructor_Test_Zero_ValidSides" time="0.002" classname="com.klindziuk.TriangleTestLab.TriangleTest">
    <error type="org.testng.TestException" message="
Method TriangleTest.constructor_Test_Zero_ValidSides()[pri:0, instance:com.klindziuk.TriangleTestLab.TriangleTest@fc185] should have thrown an exception of type class java.lang.IllegalArgumentException">
      <![CDATA[org.testng.TestException: 
Method TriangleTest.constructor_Test_Zero_ValidSides()[pri:0, instance:com.klindziuk.TriangleTestLab.TriangleTest@fc185] should have thrown an exception of type class java.lang.IllegalArgumentException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1401)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:684)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- constructor_Test_Zero_ValidSides -->
  <testcase name="constructor_Test_ValidSides_Zero" time="0.002" classname="com.klindziuk.TriangleTestLab.TriangleTest">
    <error type="org.testng.TestException" message="
Method TriangleTest.constructor_Test_ValidSides_Zero()[pri:0, instance:com.klindziuk.TriangleTestLab.TriangleTest@fc185] should have thrown an exception of type class java.lang.IllegalArgumentException">
      <![CDATA[org.testng.TestException: 
Method TriangleTest.constructor_Test_ValidSides_Zero()[pri:0, instance:com.klindziuk.TriangleTestLab.TriangleTest@fc185] should have thrown an exception of type class java.lang.IllegalArgumentException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1401)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:684)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- constructor_Test_ValidSides_Zero -->
  <testcase name="constructor_Test_ValidSide_Zero_ValidSide" time="0.020" classname="com.klindziuk.TriangleTestLab.TriangleTest">
    <error type="org.testng.TestException" message="
Method TriangleTest.constructor_Test_ValidSide_Zero_ValidSide()[pri:0, instance:com.klindziuk.TriangleTestLab.TriangleTest@fc185] should have thrown an exception of type class java.lang.IllegalArgumentException">
      <![CDATA[org.testng.TestException: 
Method TriangleTest.constructor_Test_ValidSide_Zero_ValidSide()[pri:0, instance:com.klindziuk.TriangleTestLab.TriangleTest@fc185] should have thrown an exception of type class java.lang.IllegalArgumentException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1401)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:684)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- constructor_Test_ValidSide_Zero_ValidSide -->
  <testcase name="constructor_Test_Valid_Sides" time="0.019" classname="com.klindziuk.TriangleTestLab.TriangleTest"/>
</testsuite> <!-- com.klindziuk.TriangleTestLab.TriangleTest -->
